# Generated by Django 6.0.3 on 2026-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_about_cgpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('leetcode', 'LeetCode'), ('codechef', 'CodeChef'), ('codeforces', 'Codeforces'), ('other', 'Other')], default='other', max_length=20)),
                ('username', models.CharField(max_length=120)),
                ('profile_url', models.URLField()),
                ('rating', models.CharField(blank=True, max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='coding_profiles/')),
                ('icon_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'platform', 'username'],
            },
        ),
    ]
